format_version: v1.0
type: UniqueComponent
attributes: {id: legato_gfx_pda_tm4301b}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DisplayInterface}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SSD1963}
  - type: Combo
    attributes: {id: currDisplayInterface}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: legato_gfx_pda_tm4301b, value: SSD1963}
- type: ElementPosition
  attributes: {x: '573', y: '21', id: legato_gfx_pda_tm4301b}
