configName: lcc_rgb565_mxt_mzef_cu_90
folderName: legato_qs_mzef_cu_tm4301b_90
format_version: v1.0
frameworkPath: ..\..\..\..\harmony3_dev
processor: PIC32MZ2048EFM144
projectName: legato_quickstart_mzef_cu_tm4301b_90
settings:
  PackageFilter: gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx;gfx;touch;bsp;usb;gfx;csp;gfx_apps_pic32mz_da;gfx_apps_sam_9x60;gfx_apps_pic32mz_da;core;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: ./dev_packs/arm/CMSIS/5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: ./dev_packs/Microchip/PIC32MZ-EF_DFP/1.3.58/atdf/PIC32MZ2048EFM144.atdf
