format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_hal_le}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DisplayDataEnablePolarity}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: 'true'}
  - type: Boolean
    attributes: {id: DisplayHSYNCNegative}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: 'false'}
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '480'}
  - type: Integer
    attributes: {id: DisplayHorzBackPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '40'}
  - type: Integer
    attributes: {id: DisplayHorzFrontPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '40'}
  - type: Integer
    attributes: {id: DisplayHorzPulseWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '48'}
  - type: String
    attributes: {id: DisplayName}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: PDA TM5000}
  - type: Boolean
    attributes: {id: DisplayVSYNCNegative}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: 'false'}
  - type: Integer
    attributes: {id: DisplayVertBackPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '29'}
  - type: Integer
    attributes: {id: DisplayVertFrontPorch}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '13'}
  - type: Integer
    attributes: {id: DisplayVertPulseWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '3'}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '800'}
  - type: String
    attributes: {id: DriverName}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: 'LE LCC '}
  - type: Integer
    attributes: {id: PixelClock}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: '6250000'}
  - type: Integer
    attributes: {id: RefreshRate}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_hal_le, value: '12'}
  - type: String
    attributes: {id: gfx_display}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: PDA TM5000}
  - type: String
    attributes: {id: gfx_driver}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_lcc, value: le_gfx_driver_lcc}
- type: ElementPosition
  attributes: {x: '153', y: '36', id: gfx_hal_le}
